# Generated by Django 5.1 on 2024-10-01 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verification',
            name='certification',
        ),
    ]
