# Generated by Django 5.1 on 2024-10-02 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0004_certification'),
        ('verifications', '0002_remove_verification_certification'),
    ]

    operations = [
        migrations.AddField(
            model_name='verification',
            name='certification',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='certifications.certification'),
            preserve_default=False,
        ),
    ]
