# Generated by Django 5.1 on 2026-04-02 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verifications', '0003_verification_certification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verification',
            name='verified_by',
        ),
    ]
