# Generated by Django 5.1 on 2024-09-16 12:17

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone_number', models.CharField(help_text='Enter the phone number with the country code +260 (e.g., +260XXXXXXXXX)', max_length=13, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+260XXXXXXXXX'. Up to 13 digits are allowed, and the country code +260 is required.", regex='^\\+260\\d{9}$')])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('user_type', models.CharField(choices=[('manufacturer', 'Manufacturer'), ('consumer', 'Consumer'), ('admin', 'Admin')], default='', max_length=50)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('groups', models.ManyToManyField(blank=True, related_name='custom_user_groups', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='custom_user_permissions', to='auth.permission')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='', max_length=255)),
                ('contact_person', models.CharField(default='', max_length=255)),
                ('physical_address', models.TextField(default='')),
                ('position', models.CharField(default='', max_length=255)),
                ('email', models.EmailField(default='default@example.com', max_length=254)),
                ('postal_address', models.TextField(default='')),
                ('website', models.URLField(blank=True, null=True)),
                ('mobile', models.CharField(help_text='Enter the phone number with the country code +260 (e.g., +260XXXXXXXXX)', max_length=13, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+260XXXXXXXXX'. Up to 13 digits are allowed, and the country code +260 is required.", regex='^\\+260\\d{9}$')])),
                ('site_name', models.CharField(blank=True, default='', max_length=255)),
                ('manufacturing_contact_person', models.CharField(blank=True, default='', max_length=255)),
                ('manufacturing_physical_address', models.TextField(blank=True, default='')),
                ('manufacturing_position', models.CharField(blank=True, default='', max_length=255)),
                ('manufacturing_mobile', models.CharField(blank=True, default='', max_length=20)),
                ('manufacturing_email', models.EmailField(blank=True, default='default@example.com', max_length=254)),
                ('manufacturing_postal_address', models.TextField(blank=True, default='')),
                ('factory_size_m2', models.FloatField(blank=True, default=0.0, null=True)),
                ('heard_about_zabs_recommendation', models.BooleanField(default=False, help_text='Recommendation from another company')),
                ('heard_about_zabs_search_engine', models.BooleanField(default=False, help_text='Search engine e.g. Google')),
                ('heard_about_zabs_social_media', models.BooleanField(default=False, help_text='Social media')),
                ('heard_about_zabs_other', models.BooleanField(default=False, help_text='Other')),
                ('heard_about_zabs_other_specify', models.CharField(blank=True, help_text='If other, please specify', max_length=255)),
                ('user', models.OneToOneField(limit_choices_to={'user_type': 'manufacturer'}, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
