# Generated by Django 5.1 on 2024-09-21 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='factory_size_m2',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='heard_about_zabs_other',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='heard_about_zabs_recommendation',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='heard_about_zabs_search_engine',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='heard_about_zabs_social_media',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='manufacturing_contact_person',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='manufacturing_email',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='manufacturing_mobile',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='manufacturing_physical_address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='manufacturing_position',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='manufacturing_postal_address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='site_name',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='heard_about_zabs_other_specify',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
