# Generated by Django 5.1 on 2024-09-21 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_userprofile_factory_size_m2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='heard_about_zabs_other_specify',
            new_name='Please_specify_how_you_heard_about_ZABS',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_verified',
        ),
    ]
