# Generated by Django 5.1 on 2024-09-21 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_heard_about_zabs_other_specify_userprofile_please_specify_how_you_heard_about_zabs_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user',
            new_name='manufacturer',
        ),
    ]
