# Generated by Django 5.1 on 2024-10-01 11:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_certification_id', models.CharField(blank=True, editable=False, max_length=255, unique=True)),
                ('first_issued', models.DateField(default=django.utils.timezone.now, null=True)),
                ('last_issued', models.DateField(default=django.utils.timezone.now, null=True)),
                ('modified_on', models.DateField(default=django.utils.timezone.now)),
                ('expiry_date', models.DateField(default=django.utils.timezone.now)),
                ('qr_code', models.ImageField(blank=True, upload_to='qr_codes/')),
                ('status', models.CharField(default='Approved', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CertificationApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality_mark', models.BooleanField(default=False)),
                ('certified_local_supplier', models.BooleanField(default=False)),
                ('good_food_logo', models.BooleanField(default=False)),
                ('has_target_assessment_date', models.BooleanField(default=False, help_text='Do you have a target assessment date?')),
                ('target_assessment_date', models.DateField(blank=True, help_text='If yes, please indicate the date.', null=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('reviewing', 'Reviewing'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='submitted', max_length=20)),
                ('review_comment', models.TextField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='certification_documents/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('file_name', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='', max_length=255)),
                ('description', models.CharField(default='', help_text='Description of Product', max_length=255)),
                ('brand_or_trade_name', models.CharField(default='', help_text='Brand or Trade Name', max_length=255)),
                ('standard', models.CharField(default='', help_text='Standard', max_length=255)),
                ('annual_production_quantity', models.DecimalField(decimal_places=2, default=0.0, help_text='Annual Production Quantity', max_digits=10)),
                ('unit_selling_price', models.DecimalField(decimal_places=2, default=0.0, help_text='Unit Selling Price (ZMW)', max_digits=10)),
            ],
        ),
    ]
