# Generated by Django 5.1 on 2024-10-01 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('certifications', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile'),
        ),
        migrations.AddField(
            model_name='certificationapplication',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certification_application', to='users.userprofile'),
        ),
        migrations.AddField(
            model_name='certification',
            name='certification_application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certification', to='certifications.certificationapplication'),
        ),
        migrations.AddField(
            model_name='document',
            name='certification_application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='certifications.certificationapplication'),
        ),
        migrations.AddField(
            model_name='productdetails',
            name='certification_application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product_details', to='certifications.certificationapplication'),
        ),
        migrations.AddField(
            model_name='productdetails',
            name='supporting_documents',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='certifications.document'),
        ),
        migrations.AddField(
            model_name='certification',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='certifications.productdetails'),
        ),
    ]
