# Generated by Django 5.1 on 2024-09-16 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('certifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='manufacturer',
            field=models.ForeignKey(limit_choices_to={'user_type': 'manufacturer'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='certificationapplication',
            name='manufacturer',
            field=models.ForeignKey(limit_choices_to={'user_type': 'manufacturer'}, on_delete=django.db.models.deletion.CASCADE, related_name='certification_application', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='certification',
            name='certification_application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certification', to='certifications.certificationapplication'),
        ),
        migrations.AddField(
            model_name='document',
            name='certification_application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='certifications.certificationapplication'),
        ),
        migrations.AddField(
            model_name='productdetails',
            name='certification_application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product_details', to='certifications.certificationapplication'),
        ),
        migrations.AddField(
            model_name='productdetails',
            name='supporting_documents',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='certifications.document'),
        ),
    ]
