# Generated by Django 5.1 on 2024-10-01 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0002_initial'),
        ('verifications', '0002_remove_verification_certification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Certification',
        ),
    ]
