# Generated by Django 5.1 on 2024-10-01 13:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0003_delete_certification'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_certification_id', models.CharField(blank=True, editable=False, max_length=255, unique=True)),
                ('first_issued', models.DateField(default=django.utils.timezone.now, null=True)),
                ('last_issued', models.DateField(default=django.utils.timezone.now, null=True)),
                ('modified_on', models.DateField(default=django.utils.timezone.now)),
                ('expiry_date', models.DateField(default=django.utils.timezone.now)),
                ('qr_code', models.ImageField(blank=True, upload_to='qr_codes/')),
                ('status', models.CharField(default='Approved', max_length=50)),
                ('certification_application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certification', to='certifications.certificationapplication')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='certifications.productdetails')),
            ],
        ),
    ]
