# Generated by Django 5.1 on 2024-10-09 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0004_certification'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
    ]
