# Generated by Django 5.1 on 2024-10-15 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0005_certification_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='authorized_signature',
            field=models.ImageField(null=True, upload_to='signature'),
        ),
    ]
