# Generated by Django 5.1 on 2024-10-16 09:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0006_certification_authorized_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificationapplication',
            name='application_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
